### ISSUE TITLE
Format fails when regex in query

### ISSUE THREAD

**Issue by jdubs** [laughingman7743/PyAthenaJDBC#11]
Hello,
I'm attempting to use some regex in my query and it appears that the {1,3} is causing the formatter to fail.
```
    query = """
SELECT count(backend) AS count,
         hbackend
FROM testing.{table}
WHERE REGEXP_LIKE (backend, '^\b\d{{1,3}}\.\d{{1,3}}\.\d{{1,3}}\.\d{{1,3}}\b$')
GROUP BY  backend;""".format(table=table)
    print query

try:
    with conn.cursor() as cursor:
        cursor.execute(query)
        for row in cursor:
            print(row)
finally:
    conn.close()
```
```
Traceback (most recent call last):
  File "run-queries.py", line 23, in <module>
    cursor.execute(query)
  File "/Library/Python/2.7/site-packages/pyathenajdbc/cursor.py", line 103, in execute
    query = self._formatter.format(operation, *parameter_args, **parameter_kwargs)
  File "/Library/Python/2.7/site-packages/pyathenajdbc/formatter.py", line 115, in format
    return operation.format(*args, **kwargs).strip()
KeyError: '1,3'
```

**Comment by laughingman7743** [comment]
Hi @jdubs,

If you escape curly braces one more time like this, the error seems to be fixed.
```
SELECT count(backend) AS count,
         hbackend
FROM testing.{table}
WHERE REGEXP_LIKE (backend, '^\b\d{{{{1,3}}}}\.\d{{{{1,3}}}}\.\d{{{{1,3}}}}\.\d{{{{1,3}}}}\b$')
GROUP BY  backend;
```

Thanks,

**Comment by laughingman7743** [comment]
I changed the format of the query parameter to old Python string format.
In the following branch, you should not get the error without escaping curly braces.
laughingman7743/PyAthenaJDBC#14
