### ISSUE TITLE
How to use AwsCredentialsProviderArguments

### ISSUE THREAD

**Issue by shy00n** [laughingman7743/PyAthenaJDBC#112]
Hi:

Trying to use:

AwsCredentialsProviderClass | com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider
-- | --
AwsCredentialsProviderArguments | 00000_Cor-Developer
How do I set either optional arguments or connection string base on that?
which made the Dbeaver work as the key pair is in %userprofile%\.aws\credentials
Thanks,

Sam,

**Comment by laughingman7743** [comment]
You can connect to Athena by specifying the profile name in the "Profile" argument as follows:
```
connect(
    Profile='00000_Cor-Developer',
    S3OutputLocation='s3://BUCKET/',
    AwsRegion='us-west-2'
)
```

**Comment by shy00n** [comment]
Thank you but now I get a different error:
```
>>> conn = connect(
...     Profile=profile,
...     S3OutputLocation="s3://test-delete-b/simba_tmp/",
...     AwsRegion='us-east-1')
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "C:\Users\alive\.pyenv\pyenv-win\versions\Cor_Demo\lib\site-packages\pyathenajdbc\__init__.py", line 82, in connect
    return Connection(*args, **kwargs)
  File "C:\Users\alive\.pyenv\pyenv-win\versions\Cor_Demo\lib\site-packages\pyathenajdbc\connection.py", line 55, in __init__
    ATHENA_CONNECTION_STRING.format(region=self.region_name), props
jpype._jclass.SQLException: java.sql.SQLException: [Simba][AthenaJDBC](100191) Failed to create AWS Credentials Provider class: The values of the connection properties profile is in conflict with AwsCredentialsProviderClass.
```

**Comment by laughingman7743** [comment]
Sorry. It looks like I'm specifying it the wrong way. 🙇‍♂️ 
I was able to confirm that I can connect with the following settings:
```
conn = connect(S3OutputLocation='s3://BUCKET/path/to/',
               AwsRegion='us-west-2',
               AwsCredentialsProviderClass='com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider',
               AwsCredentialsProviderArguments='your_profile_name')
```
Try it out. 🙏

**Comment by shy00n** [comment]
We now have a firing solution! Thank you,
