### ISSUE TITLE
java.lang.RuntimeException: Class com.amazonaws.athena.jdbc.AthenaDriver not found

### ISSUE THREAD

**Issue by gallamine** [laughingman7743/PyAthenaJDBC#34]
Running Java 8 on OSX. Installed PyAthenaJDBC via pip. Python 3.6.

```
from pyathenajdbc import connect
conn = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',region_name='us-west-2')
```
```
---------------------------------------------------------------------------
java.lang.RuntimeExceptionPyRaisable      Traceback (most recent call last)
<ipython-input-2-d12b72b4e202> in <module>()
      1 conn = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
----> 2                region_name='us-west-2')
      3

~/anaconda/envs/python-jdbc/lib/python3.6/site-packages/pyathenajdbc/__init__.py in connect(s3_staging_dir, access_key, secret_key, region_name, schema_name, profile_name, credential_file, jvm_path, jvm_options, converter, formatter, driver_path, **kwargs)
     64                       region_name, schema_name, profile_name, credential_file,
     65                       jvm_path, jvm_options, converter, formatter,
---> 66                       driver_path, **kwargs)

~/anaconda/envs/python-jdbc/lib/python3.6/site-packages/pyathenajdbc/connection.py in __init__(self, s3_staging_dir, access_key, secret_key, region_name, schema_name, profile_name, credential_file, jvm_path, jvm_options, converter, formatter, driver_path, **driver_kwargs)
     67
     68         props = self._build_driver_args(**driver_kwargs)
---> 69         jpype.JClass(ATHENA_DRIVER_CLASS_NAME)
     70         self._jdbc_conn = jpype.java.sql.DriverManager.getConnection(
     71             ATHENA_CONNECTION_STRING.format(region=self.region_name, schema=schema_name), props)

~/anaconda/envs/python-jdbc/lib/python3.6/site-packages/jpype/_jclass.py in JClass(name)
     53     jc = _jpype.findClass(name)
     54     if jc is None:
---> 55         raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
     56
     57     return _getClassFor(jc)

java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.amazonaws.athena.jdbc.AthenaDriver not found
```

```
$ java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
```

**Comment by laughingman7743** [comment]
There is no problem in my environment. Please check if there is a JAR file in the site-package directory (/path/to/python3.6/site-package/pyathenajdbc/AthenaJDBC41-1.1.0.jar).
```
Laughingman7743-no-MacBook-Air:~ laughingman7743$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1510

Laughingman7743-no-MacBook-Air:~ laughingman7743$ python -V
Python 3.6.1

Laughingman7743-no-MacBook-Air:~ laughingman7743$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

Laughingman7743-no-MacBook-Air:~ laughingman7743$ pip freeze
botocore==1.5.78
docutils==0.13.1
future==0.16.0
jmespath==0.9.3
JPype1==0.6.2
PyAthenaJDBC==1.1.2
python-dateutil==2.6.0
six==1.10.0

Laughingman7743-no-MacBook-Air:~ laughingman7743$ python -c "from pyathenajdbc import connect;conn = connect(s3_staging_dir='s3://laughingman7743/circleci/',region_name='us-west-2')"
log4j:WARN No appenders could be found for logger (com.amazonaws.athena.jdbc.AthenaDriver).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by laughingman7743** [comment]
Currently boto3 supports Athena.
http://boto3.readthedocs.io/en/latest/reference/services/athena.html

I think that it is the best way to use boto3.
If you want to use the Python DB API interface, you should use PyAthena(https://github.com/laughingman7743/PyAthena) on the boto3 base.

**Comment by gallamine** [comment]
I verified that `AthenaJDBC41-1.1.0.jar` is contained in `/Users/william/anaconda/envs/python-jdbc/lib/python3.6/site-packages/pyathenajdbc`

```
(python-jdbc) william @ ~/Documents/  (master) $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F2411

(python-jdbc) william @ ~/Documents/  (master) $ pip freeze
botocore==1.5.78
docutils==0.13.1
future==0.16.0
jmespath==0.9.3
JPype1==0.6.2
PyAthenaJDBC==1.1.2
python-dateutil==2.6.0
six==1.10.0

(python-jdbc) william @ ~/Documents/  (master) $ python -V
Python 3.6.1 :: Continuum Analytics, Inc.

(python-jdbc) william @ ~/Documents/  (master) $ java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

(python-jdbc) william @ ~/Documents/  (master) $ python -c "from pyathenajdbc import connect;conn = connect(s3_staging_dir='s3://laughingman7743/circleci/',region_name='us-west-2')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/william/anaconda/envs/python-jdbc/lib/python3.6/site-packages/pyathenajdbc/__init__.py", line 66, in connect
    driver_path, **kwargs)
  File "/Users/william/anaconda/envs/python-jdbc/lib/python3.6/site-packages/pyathenajdbc/connection.py", line 69, in __init__
    jpype.JClass(ATHENA_DRIVER_CLASS_NAME)
  File "/Users/william/anaconda/envs/python-jdbc/lib/python3.6/site-packages/jpype/_jclass.py", line 55, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.amazonaws.athena.jdbc.AthenaDriver not found
```

**Comment by laughingman7743** [comment]
It seems you are using condan's venv. I will try creating a similar environment.
The connect method can specify the path of the JDBC driver as follows.
```
conn = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
               region_name='us-west-2',
               driver_path='/path/to/python3.6/site-packages/pyathenajdbc/AthenaJDBC41-1.1.0.jar')
```
What if you explicitly specify driver_path?

**Comment by gallamine** [comment]
I have tried specifying the exact path to the driver but get the same error. 

```
$ python -c "from pyathenajdbc import connect;conn = connect(s3_staging_dir='s3://<my bucket>/path/to/',region_name='us-east-1',driver_path='/Users/william/anaconda/envs/python-jdbc/lib/python3.6/site-packages/pyathenajdbc/AthenaJDBC41-1.1.0.jar')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/william/anaconda/envs/python-jdbc/lib/python3.6/site-packages/pyathenajdbc/__init__.py", line 66, in connect
    driver_path, **kwargs)
  File "/Users/william/anaconda/envs/python-jdbc/lib/python3.6/site-packages/pyathenajdbc/connection.py", line 69, in __init__
    jpype.JClass(ATHENA_DRIVER_CLASS_NAME)
  File "/Users/william/anaconda/envs/python-jdbc/lib/python3.6/site-packages/jpype/_jclass.py", line 55, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.amazonaws.athena.jdbc.AthenaDriver not found
```

Here is the contents of my environment.yml file that I used to build the Conda environment:

```
name: python-jdbc
dependencies:
  - python=3.6
  - pip:
    - botocore==1.5.78
    - docutils==0.13.1
    - future==0.16.0
    - jmespath==0.9.3
    - JPype1==0.6.2
    - PyAthenaJDBC==1.1.2
    - python-dateutil==2.6.0
    - six==1.10.0
```

**Comment by laughingman7743** [comment]
I used pyenv to create the same virtual environment on Anaconda and tried it, but there was no problem. :tired_face:
```
Laughingman7743-no-MacBook-Air:tmp laughingman7743$ pyenv install anaconda3-4.3.1
Downloading Anaconda3-4.3.1-MacOSX-x86_64.sh...
-> https://repo.continuum.io/archive/Anaconda3-4.3.1-MacOSX-x86_64.sh
Installing Anaconda3-4.3.1-MacOSX-x86_64...
Installed Anaconda3-4.3.1-MacOSX-x86_64 to /Users/laughingman7743/.pyenv/versions/anaconda3-4.3.1

Laughingman7743-no-MacBook-Air:tmp laughingman7743$ pyenv local anaconda3-4.3.1
Laughingman7743-no-MacBook-Air:tmp laughingman7743$ python -V
Python 3.6.0 :: Anaconda 4.3.1 (x86_64)

Laughingman7743-no-MacBook-Air:tmp laughingman7743$ conda env create -f environment.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
openssl-1.0.2l 100% |##########################################################################################################################| Time: 0:00:01   2.20 MB/s
readline-6.2-2 100% |##########################################################################################################################| Time: 0:00:00 977.27 kB/s
sqlite-3.13.0- 100% |##########################################################################################################################| Time: 0:00:01   1.34 MB/s
tk-8.5.18-0.ta 100% |##########################################################################################################################| Time: 0:00:00   2.58 MB/s
xz-5.2.2-1.tar 100% |##########################################################################################################################| Time: 0:00:00   2.29 MB/s
zlib-1.2.8-3.t 100% |##########################################################################################################################| Time: 0:00:00   2.22 MB/s
python-3.6.1-2 100% |##########################################################################################################################| Time: 0:00:06   1.87 MB/s
setuptools-27. 100% |##########################################################################################################################| Time: 0:00:00   2.20 MB/s
wheel-0.29.0-p 100% |##########################################################################################################################| Time: 0:00:00   2.65 MB/s
pip-9.0.1-py36 100% |##########################################################################################################################| Time: 0:00:01   1.07 MB/s
Collecting botocore==1.5.78
  Using cached botocore-1.5.78-py2.py3-none-any.whl
Collecting docutils==0.13.1
  Using cached docutils-0.13.1-py3-none-any.whl
Collecting future==0.16.0
Collecting jmespath==0.9.3
  Using cached jmespath-0.9.3-py2.py3-none-any.whl
Collecting JPype1==0.6.2
Collecting PyAthenaJDBC==1.1.2
  Using cached PyAthenaJDBC-1.1.2-py2.py3-none-any.whl
Collecting python-dateutil==2.6.0
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting six==1.10.0
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: docutils, jmespath, six, python-dateutil, botocore, future, JPype1, PyAthenaJDBC
Successfully installed JPype1-0.6.2 PyAthenaJDBC-1.1.2 botocore-1.5.78 docutils-0.13.1 future-0.16.0 jmespath-0.9.3 python-dateutil-2.6.0 six-1.10.0
#
# To activate this environment, use:
# > source activate python-jdbc
#
# To deactivate this environment, use:
# > source deactivate python-jdbc
#

Laughingman7743-no-MacBook-Air:tmp laughingman7743$ source ~/.pyenv/versions/anaconda3-4.3.1/envs/python-jdbc/bin/activate python-jdbc

(python-jdbc) Laughingman7743-no-MacBook-Air:tmp laughingman7743$ python -V
Python 3.6.1 :: Continuum Analytics, Inc.

(python-jdbc) Laughingman7743-no-MacBook-Air:tmp laughingman7743$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

(python-jdbc) Laughingman7743-no-MacBook-Air:tmp laughingman7743$ pip freeze
botocore==1.5.78
docutils==0.13.1
future==0.16.0
jmespath==0.9.3
JPype1==0.6.2
PyAthenaJDBC==1.1.2
python-dateutil==2.6.0
six==1.10.0

(python-jdbc) Laughingman7743-no-MacBook-Air:tmp laughingman7743$ python -c "from pyathenajdbc import connect;conn = connect(s3_staging_dir='s3://laughingman7743/circleci/',region_name='us-west-2')"
log4j:WARN No appenders could be found for logger (com.amazonaws.athena.jdbc.AthenaDriver).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by gallamine** [comment]
I upgraded OSX from 10.10.5 to Sierra (10.12.6) and everything seems to work fine.
Thanks for your help.

**Comment by rohan-kekatpure** [comment]
Had a similar issue and found this thread very helpful. In my case, my environment variable `JAVA_HOME` was not set to a valid value. Once I fixed that, the code below worked.

```
from pyathenajdbc import connect

s3_staging_dir = 's3://path/to/s3dir'
region_name = 'us-west-2'
conn = connect(s3_staging_dir=s3_staging_dir,region_name=region_name)
```

**Comment by kws-slalom** [comment]
I am having this same issue.  I checked my JAVA_HOME env variable indeed it was unset.  I fixed that issue by runnung `export $JAVA_HOME=/usr/bin/java` and its throwing the error.

```
ava.lang.RuntimeExceptionPyRaisable      Traceback (most recent call last)
<ipython-input-4-4016b24d1a0f> in <module>
      3                acccess_key='XXXXXXXXXXXXXXXXXXXX',
      4                secret_key='XXXXXXXXXXXXXXXXXXXX',
----> 5                driver_path='/Users/myusername/drivers/AthenaJDBC42_2.0.7.jar')

/anaconda3/envs/linear_opt_3.7/lib/python3.7/site-packages/pyathenajdbc/__init__.py in connect(s3_staging_dir, access_key, secret_key, region_name, schema_name, profile_name, credential_file, jvm_path, jvm_options, converter, formatter, driver_path, log4j_conf, **kwargs)
     67                       region_name, schema_name, profile_name, credential_file,
     68                       jvm_path, jvm_options, converter, formatter,
---> 69                       driver_path, log4j_conf, **kwargs)

/anaconda3/envs/linear_opt_3.7/lib/python3.7/site-packages/pyathenajdbc/connection.py in __init__(self, s3_staging_dir, access_key, secret_key, region_name, schema_name, profile_name, credential_file, jvm_path, jvm_options, converter, formatter, driver_path, log4j_conf, **driver_kwargs)
     69 
     70         props = self._build_driver_args(**driver_kwargs)
---> 71         jpype.JClass(ATHENA_DRIVER_CLASS_NAME)
     72         self._jdbc_conn = jpype.java.sql.DriverManager.getConnection(
     73             ATHENA_CONNECTION_STRING.format(region=self.region_name, schema=schema_name), props)

/anaconda3/envs/linear_opt_3.7/lib/python3.7/site-packages/jpype/_jclass.py in JClass(name)
     71     jc = _jpype.findClass(name)
     72     if jc is None:
---> 73         raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
     74 
     75     return _getClassFor(jc)

java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.simba.athena.jdbc.Driver not found
```
