### ISSUE TITLE
1.3.1 seems to hide syntax errors

### ISSUE THREAD

**Issue by abridgett** [laughingman7743/PyAthenaJDBC#54]
Running a (broken) query on v1.1.1:
```
ERROR    Failed to execute query.
Traceback (most recent call last):
  File ".../pyathenajdbc/cursor.py", line 117, in execute
    result_set = self._statement.executeQuery(query)
jpype._jexception.java.sql.SQLExceptionPyRaisable: java.sql.SQLException: Failed to run query
ERROR    line 89:22: mismatched input 'IN' expecting {')', 'GROUP', 'ORDER', 'HAVING', 'LIMIT', 'OR', 'AND', 'UNION', 'EXCEPT', 'INTERSECT'} (Service: AmazonAthena; Status Code: 400; Error Code: InvalidRequestException; Request ID: 14660a88-118e-11e8-b0e3-6d7bda9bea82)
```

However with v1.3.1 those really handy details seem lost:
```
ERROR    Failed to execute query.
Traceback (most recent call last):
  File ".../pyathenajdbc/cursor.py", line 172, in execute
    result_set = self._statement.executeQuery(query)
jpype._jexception.java.sql.SQLExceptionPyRaisable: java.sql.SQLException: Failed to run query
ERROR    java.sql.SQLException: Failed to run query
```
I think this is the change that changed this:
https://github.com/laughingman7743/PyAthenaJDBC/commit/c2535863738f1bde8ab3dab959e78b6a1fb38089

I've tried to workaround this by putting that logic in my code but it looks like the data is lost (presumably as the exception is reraised)

**Comment by laughingman7743** [comment]
I think that the difference in error message may be due to the difference in version of JDBC driver.
The correspondence of JDBC driver version is as follows.

version | JDBC driver version
--- | ---
v1.1.1 | AthenaJDBC41-1.0.1
v1.3.1 | AthenaJDBC41-1.1.0

Please let me know the table definition and the query where the error occurred.

Thanks,

**Comment by abridgett** [comment]
Gosh - that was fast! It looks like not the JDBC driver change:

I'm running this SQL:
```
select count(*) from speed_augmented_v2 where dt='2018-01-01' and client_code in %(app_list)s
```
Our wrapper didn't support lists (now fixed) so app_list was a string rather than list object which caused the SQL error.

On PyAthenaJDBC v1.1.1 (AthenaJDBC v1.0.1):
```
2018-02-15 14:21:53,640 ERROR    Failed to execute query.
Traceback (most recent call last):
  File "/Users/adrian/projects/os/data-athena/venv/lib/python3.6/site-packages/pyathenajdbc/cursor.py", line 117, in execute
    result_set = self._statement.executeQuery(query)
jpype._jexception.java.sql.SQLExceptionPyRaisable: java.sql.SQLException: Failed to run query
2018-02-15 14:21:53,646 ERROR    line 1:79: mismatched input 'in' expecting {<EOF>, 'GROUP', 'ORDER', 'HAVING', 'LIMIT', 'OR', 'AND', 'UNION', 'EXCEPT', 'INTERSECT'} (Service: AmazonAthena; Status Code: 400; Error Code: InvalidRequestException; Request ID: 91ff6d70-125b-11e8-a10f-e52a7edfa5db)
```

On PyAthenaJDBC v1.3.1 (AthenaJDBC v1.1.0):
```
2018-02-15 14:22:52,618 ERROR    Failed to execute query.
Traceback (most recent call last):
  File "/Users/adrian/projects/os/data-athena/venv/lib/python3.6/site-packages/pyathenajdbc/cursor.py", line 172, in execute
    result_set = self._statement.executeQuery(query)
jpype._jexception.java.sql.SQLExceptionPyRaisable: java.sql.SQLException: Failed to run query
2018-02-15 14:22:52,706 ERROR    java.sql.SQLException: Failed to run query
```

Now trying with the alternative JDBC drivers:

On PyAthenaJDBC v1.1.1 (AthenaJDBC v1.1.0):
```
2018-02-15 14:26:23,327 ERROR    Failed to execute query.
Traceback (most recent call last):
  File "/Users/adrian/projects/os/data-athena/venv/lib/python3.6/site-packages/pyathenajdbc/cursor.py", line 117, in execute
    result_set = self._statement.executeQuery(query)
jpype._jexception.java.sql.SQLExceptionPyRaisable: java.sql.SQLException: Failed to run query
2018-02-15 14:26:23,333 ERROR    line 1:79: mismatched input 'in' expecting {<EOF>, 'GROUP', 'ORDER', 'HAVING', 'LIMIT', 'OR', 'AND', 'UNION', 'EXCEPT', 'INTERSECT'} (Service: AmazonAthena; Status Code: 400; Error Code: InvalidRequestException; Request ID: 32b8e811-125c-11e8-a9cb-57f70b9cca77)
```

On PyAthenaJDBC v1.3.1 (AthenaJDBC v1.0.1):
```
2018-02-15 14:24:31,141 ERROR    Failed to execute query.
Traceback (most recent call last):
  File "/Users/adrian/projects/os/data-athena/venv/lib/python3.6/site-packages/pyathenajdbc/cursor.py", line 172, in execute
    result_set = self._statement.executeQuery(query)
jpype._jexception.java.sql.SQLExceptionPyRaisable: java.sql.SQLException: Failed to run query
2018-02-15 14:24:31,237 ERROR    java.sql.SQLException: Failed to run query
```

**Comment by laughingman7743** [comment]
Thank you for the quick reply.
I understand that it is not a difference in JDBC driver version.
Please also let me know the version of Python you are running.

I think that the implementation before change is somewhat dirty. I will think about the smart implementation by hand over the error information on the weekend.
Please tell me if you know something good implementation method :)

**Comment by laughingman7743** [comment]
```
  File "/Users/adrian/projects/os/data-athena/venv/lib/python3.6/site-packages/pyathenajdbc/cursor.py", line 172, in execute
```
The execution environment is Python 3.6.

**Comment by laughingman7743** [comment]
Sorry for the late reply.
I fixed this issue with the following pull request. Please check it.
https://github.com/laughingman7743/PyAthenaJDBC/pull/55

Well, it has not changed much from the previous implementation 😂 
Thanks,

**Comment by abridgett** [comment]
super - that works well here - saves a load of time figuring out what's wrong :-)
